name: Simple Issue Labeler
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: initial labeling
      uses: andymckay/labeler@1.0.3
      with:
        add-labels: "test-label"
