name: Auto Assign to Project(s)

on:
  issues:
    types:
      - reopened
      - opened

env:
  MY_GITHUB_TOKEN: ${{ secrets.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 }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event_name == 'opened'
      with:
        project: 'https://github.com/users/SamMacy/projects/2'
