# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: Auto Assign issue to Project

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
  REPO_URL: ${{ github.event.repository.url}}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issues in repo with topics to repositories
      uses: Senzing/github-action-add-issue-to-project@issue-3.macy.1
      with:
        project1: 'https://github.com/users/SamMacy/projects/2'
        project2: 'https://github.com/SamMacy/playground/projects/2'
        topic1: 't-comm'
        topic2: 't-ast'
        column_name: 'Backlog'
