name: Auto Assign to Project(s)

on:
  issues:
    types:
      - reopened
      - opened

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign NEW issues requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/SamMacy/Jupyter/projects/2'
