name: Auto Assign to Project(s)

on:
  issues:
    types:
      - reopened
      - opened

env:
  MY_GITHUB_TOKEN: ${{ secrets.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 }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/users/SamMacy/projects/2'
