# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: issue test

on:
  issues:
    types:
      - opened
env:
  GITHUB_TOKEN: ${{ secrets.ORG_MEMBERSHIP_TOKEN }}
  MEMBER_LIST: ${{ secrets.SENZING_MEMBERS }}
  CREATOR: ${{ github.actor }}
  TOKEN: ${{ secrets.SENZING_SLACK_BEARER_TOKEN }}

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
    - name: run script
      env:
          BOOL: ${{ contains( env.MEMBER_LIST, env.CREATOR ) }}
      if: ${{ env.BOOL == 'true' }
      uses: SamMacy/Get-issue-creator@master
