on: 
  issues:
    types:
      - opened
jobs:
  get_issue_maker: 
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue maker: ${{ github.actor }}"
