# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: members

on:
  issues:
    types:
      - opened
env:
  GITHUB_TOKEN: ${{ secrets.ORG_MEMBERSHIP_TOKEN }}
#  MEMBER_LIST: ${{ env.SENZING_MEMBERS }}
#  CREATOR: ${{ github.actor }}
#  BOOL: ${{ contains( ${MEMBER_LIST}, ${CREATOR} ) }}

jobs:
  check-membership:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: SamMacy/Get-issue-creator@master
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python script.py
